name: Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build and Sign APK
      run: ./gradlew assembleRelease
    - name: Rename APK
      run: mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/QuickGlance.apk
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: QuickGlance.apk
        path: app/build/outputs/apk/release/QuickGlance.apk

  create-release:
    needs: [build-android]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download APK artifact
        uses: actions/download-artifact@v3
        with:
          name: QuickGlance.apk
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            QuickGlance.apk
 
